package org.example;

public enum EventType {
    STRENGTH_ELIXIR, AGILITY_ELIXIR, MAX_HEALTH_ELIXIR,
    APPLE, BREAD, MEAT,
    STRENGTH_SCROLL, AGILITY_SCROLL, MAX_HEALTH_SCROLL,
    STICK, KNIFE, HAMMER, AXE,
    TREASURE, NONE,

    HERO_HIT_SUCCESS, HERO_HIT_FAIL, KILL_ENEMY,
    ENEMY_HIT_SUCCESS, ENEMY_HIT_FAIL,
    ENEMY_IS_STUNNED, HERO_IS_STUNNED
}
